import React from 'react';
import SideBar from '../../components/SideBar';
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Car Trucker-Dashboard",
  description: "Generated by create next app",
};
const DashboardLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (

      <div className="flex max-h- gap-2 bg-slate-50 max-container text-blue-800 dark:text-slate-50 dark:bg-gray-800
      ">
        <SideBar />
        <main className="flex-1 p-4 w-full rounded-xl bg-gray-100 h-[calc(100vh-5.1rem)] bg-gray-200 dark:bg-blue-950
        shadow-xl shadow-blue-gray-900/5  mt-1 overflow-y-scroll z-50 no-scrollbar overscroll-auto dark:bg-blue-950">
          {children}
          </main>
      </div>
  );
};

export default DashboardLayout;